spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp


database:
  username: whereboy
  password: where1234
  url: jdbc:mysql://wheredatabase.cplrxb3kh41a.ap-northeast-2.rds.amazonaws.com:3306/wyaDB?characterEncoding=utf8
  driverClass: com.mysql.jdbc.Driver


jwt:
  secret: 12345678901234567890123456789012


cloud:
  aws:
    s3:
      bucket: gogoeverybodyy
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instanceProfile: true # AWS CLI에서 aws configure list 정보를 반영할건지 여부
      accessKey: AKIAWZMLK2OGUXD2YHWK
      secretKey: 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
